# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_blowfish')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_blowfish')
    _blowfish = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_blowfish', [dirname(__file__)])
        except ImportError:
            import _blowfish
            return _blowfish
        if fp is not None:
            try:
                _mod = imp.load_module('_blowfish', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _blowfish = swig_import_helper()
    del swig_import_helper
else:
    import _blowfish
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def BF_set_key(key, len, data):
    return _blowfish.BF_set_key(key, len, data)
BF_set_key = _blowfish.BF_set_key

def BF_encrypt(data, key):
    return _blowfish.BF_encrypt(data, key)
BF_encrypt = _blowfish.BF_encrypt

def BF_decrypt(data, key):
    return _blowfish.BF_decrypt(data, key)
BF_decrypt = _blowfish.BF_decrypt

def BF_ecb_encrypt(arg1, out, key, enc):
    return _blowfish.BF_ecb_encrypt(arg1, out, key, enc)
BF_ecb_encrypt = _blowfish.BF_ecb_encrypt

def BF_cbc_encrypt(arg1, out, length, schedule, ivec, enc):
    return _blowfish.BF_cbc_encrypt(arg1, out, length, schedule, ivec, enc)
BF_cbc_encrypt = _blowfish.BF_cbc_encrypt

def BF_cfb64_encrypt(arg1, out, length, schedule, ivec, num, enc):
    return _blowfish.BF_cfb64_encrypt(arg1, out, length, schedule, ivec, num, enc)
BF_cfb64_encrypt = _blowfish.BF_cfb64_encrypt

def BF_ofb64_encrypt(arg1, out, length, schedule, ivec, num):
    return _blowfish.BF_ofb64_encrypt(arg1, out, length, schedule, ivec, num)
BF_ofb64_encrypt = _blowfish.BF_ofb64_encrypt

def BF_zipit(data, data_len, key, key_len, encrypt, level):
    return _blowfish.BF_zipit(data, data_len, key, key_len, encrypt, level)
BF_zipit = _blowfish.BF_zipit
# This file is compatible with both classic and new-style classes.


